OPENAI_API_KEY = "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"

[supabase]
url = "https://nkgtnqkqfstmxeqmuqro.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZ3RucWtxZnN0bXhlcW11cXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwMjM3NDUsImV4cCI6MjA4MjU5OTc0NX0.-4kKJkI9XEyuZhH1csNSCiuHCNlv79yg-c2s_jZEPS0"